#101 query updated
WebUI-Project-Based-07-nr/BackEnd pull request #102
Opened 2024-08-11 11:30 UTC by miller-113

2024-08-11 11:30 UTC, markgol777 approved these changes
amazing.

2024-08-11 20:08 UTC, CallMeMaverick approved these changes

2024-08-12 15:31 UTC, nrevutska requested changes

2024-08-12 15:31 UTC, nrevutska commented on src/utils/categories/categoriesAggregateOptions.js
> +        // offers: { $exists: true, $ne: [] }
remove these comments

2024-08-12 15:48 UTC, nrevutska approved these changes

2024-08-12 15:49 UTC, merged