Fix failing tests
WebUI-Project-Based-07-nr/BackEnd pull request #105
Opened 2024-08-12 11:29 UTC by CallMeMaverick

# Description
Quite a few tests are failing, those must be addressed.

# Acceptance criteria
- [x] All tests pass successfully

<img width="622" alt="image" src="https://github.com/user-attachments/assets/85b31d62-e2f2-483f-a327-e38b8dced2ed">

Closes #86

2024-08-12 11:38 UTC, miller-113 approved these changes

2024-08-12 15:26 UTC, nrevutska requested changes

2024-08-12 15:26 UTC, nrevutska commented on src/utils/testUserAuth.js
> +  const loginUserResponse = await app.post('/auth/login').send({ email: testUser.email, password: 'Qwerty123@' })
this should've stayed the way it was

2024-08-13 15:31 UTC, nrevutska approved these changes

2024-08-13 20:21 UTC, merged