Test/31/user service integration
WebUI-Project-Based-07-nr/BackEnd pull request #39
Opened 2024-07-15 20:29 UTC by miller-113

The PR contains integration test for user services.
<img width="1503" alt="Screenshot 2024-07-15 at 23 25 34" src="https://github.com/user-attachments/assets/f5dcfe02-12be-4ae1-b197-cd1eefa38e3a">
<img width="586" alt="Screenshot 2024-07-15 at 23 25 43" src="https://github.com/user-attachments/assets/3dc0ac6e-b164-47b7-8879-78b7849af5bb">

2024-07-15 20:36 UTC, CallMeMaverick approved these changes
Looks good to me 👍🏻

2024-07-16 06:46 UTC, kryzanivska-nastya approved these changes

2024-07-16 09:19 UTC, Yaroslav-Yakovlev approved these changes

2024-07-16 16:25 UTC, nrevutska requested changes

2024-07-16 16:25 UTC, nrevutska commented on src/test/integration/services/user.spec.js
> +  test('createError should create error with specific status and message', () => {
it looks like this test should be placed somewhere else, because it does not test the functionality of  User

2024-07-17 21:00 UTC, nrevutska approved these changes

2024-07-18 07:17 UTC, merged