Test/34/auth service intergration
WebUI-Project-Based-07-nr/BackEnd pull request #42
Opened 2024-07-16 19:20 UTC by miller-113

The PR contain integration test for auth.

2024-07-17 08:56 UTC, Yaroslav-Yakovlev approved these changes

2024-07-17 09:00 UTC, CallMeMaverick approved these changes

2024-07-17 12:35 UTC, kryzanivska-nastya approved these changes

2024-07-17 20:53 UTC, nrevutska requested changes
only this file is related to the task
src/test/integration/services/auth.spec.js

2024-07-24 15:20 UTC, nrevutska approved these changes

2024-07-24 18:24 UTC, merged