done
WebUI-Project-Based-07-nr/BackEnd pull request #44
Opened 2024-07-17 15:32 UTC by markgol777

2024-07-17 15:58 UTC, CallMeMaverick approved these changes

2024-07-17 18:28 UTC, Bakalina approved these changes

2024-07-18 07:24 UTC, miller-113 approved these changes

2024-07-18 07:24 UTC, miller-113 commented on src/services/offer.js
why you deleting exec()?

2024-07-18 09:08 UTC, markgol777 commented on src/services/offer.js
unit test was giving me an error with it

2024-07-18 09:23 UTC, nrevutska requested changes

2024-07-18 09:23 UTC, nrevutska commented on src/services/offer.js
in most cases, it's not a good approach to change the source code in favor of tests, unless it is some code improvement.
Here you should leave that exec and make changes to your mock of findByIdAndRemove (take a look at mock of Offer.aggregate as an example)

2024-07-18 17:54 UTC, Yaroslav-Yakovlev approved these changes

2024-07-24 15:21 UTC, nrevutska approved these changes

2024-07-25 14:13 UTC, merged