Resolve CI Pipeline Failures
WebUI-Project-Based-07-nr/BackEnd pull request #50
Opened 2024-07-18 13:34 UTC by CallMeMaverick

Closes #45

2024-07-18 21:59 UTC, Bakalina approved these changes

2024-07-19 09:13 UTC, kryzanivska-nastya approved these changes

2024-07-19 09:16 UTC, miller-113 approved these changes

2024-07-23 13:59 UTC, nrevutska requested changes
Presented code does not resolve CI Pipeline Failures
Either it should be linked to another issue, or other changes should be presented

2024-07-23 17:15 UTC, CallMeMaverick commented
The only thing to do was to add proper secrets to the GitHub repo. After that tests were not noticed to fail at any point

2024-07-23 17:26 UTC, nrevutska commented
create corresponding task to the changes. This is not the right task for it.

2024-07-23 17:50 UTC, closed without merging