Integration test for question controller
WebUI-Project-Based-07-nr/BackEnd pull request #55
Opened 2024-07-19 10:10 UTC by CallMeMaverick

Implemented integration test for question controller:
<img width="807" alt="image" src="https://github.com/user-attachments/assets/52cbf3ac-20e7-4fbf-a391-5009236c9038">
**100%** Statements (33/33)
**100%** Branches (0/0)
**100%** Functions (5/5)
**100%** Lines (33/33)

Closes #54

2024-07-19 10:20 UTC, Yaroslav-Yakovlev approved these changes

2024-07-19 11:35 UTC, mistercapxx approved these changes

2024-07-19 12:16 UTC, Bakalina approved these changes

2024-07-23 14:28 UTC, nrevutska requested changes
tests in this pr do not test the actual logic, just the code written in the test file itself

2024-07-25 07:30 UTC, nrevutska approved these changes

2024-07-25 08:49 UTC, merged