Location service
WebUI-Project-Based-07-nr/BackEnd pull request #65
Opened 2024-07-24 12:17 UTC by CallMeMaverick

This PR introduces the location service that fetches the countries from [CountryStateCity API](https://countrystatecity.in/). Both the controller and service are covered by tests. The endpoint was tested using Postman.

# Tests
### Service:
<img width="692" alt="image" src="https://github.com/user-attachments/assets/c85f672d-4a3c-4240-8127-c4fb0f7de019">

### Controller:
<img width="635" alt="image" src="https://github.com/user-attachments/assets/354823ed-13fc-46d0-930e-ff87cd4cba54">

# Swagger
### Respective Swagger Docs have been updated accordingly:
<img width="1447" alt="image" src="https://github.com/user-attachments/assets/5baad29e-4540-49ca-a8d7-58c1aab87544">

Closes #57

2024-07-24 12:54 UTC, miller-113 approved these changes

2024-07-25 07:44 UTC, kryzanivska-nastya approved these changes

2024-07-25 19:14 UTC, Yaroslav-Yakovlev approved these changes

2024-07-26 08:28 UTC, kryzanivska-nastya approved these changes

2024-07-26 09:07 UTC, markgol777 approved these changes

2024-07-29 15:24 UTC, nrevutska requested changes
Please, fix the case with expect in catch block

2024-07-29 15:24 UTC, nrevutska commented on src/test/unit/services/location.spec.js
> +            expect(error).toEqual(mockError)
expect in a catch block not a good practice
use [this](https://jestjs.io/docs/expect#tothrowerror) approach

2024-07-29 16:27 UTC, nrevutska approved these changes

2024-07-29 16:30 UTC, merged